### ISSUE TITLE
Allow specifying folders to run specific commands from relative to config file

### ISSUE THREAD

**Issue by SeinopSys** [blunt1337/wtfcmd#5]
I've been loving wtfcmd since I first came across it, and it's helped me save a ton of time so far. I recently saw the need to add commands that need to be run from specific directories to output files into said directory no matter where it's being run from, and currently the only way to signal this is to add the name of the directory to the description of the command.

I want to suggest adding a config option (e.g. `cd`) to the command block that'd force the command to start in a specific folder relative to the config file. For example, with a config file located at `/home/user/project/.wtfcmd.json` and a command that must be run after `cd`ing into `/home/user/project/public/`, you could specify in the config file:

```json
[
  {
    "name": "mycommand",
    "desc": "Generates a file into the public directory",
    "cmd": "some-command generate --output file.json",
    "cd": "public",
  }
]
```

and this would run the specified command with the current working directory of `/home/user/project/public/` regardless of which subfolder the user was in when running it.

**Comment by blunt1337** [comment]
Ok sounds good, we can call it "cwd" for "current working directory" instead, it's more conventional.

**Comment by SeinopSys** [comment]
Thank you! In CMDs.md you forgot to add `**` after "**Optional" in the new section, you might want to fix that
